version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    image: alanlisboa/node-app-c2
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=9632
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    image: "alanlisboa/nginx-c2"
    ports:
      - "5000:80"
    networks:
      - node-network      
    depends_on:
      - app

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
